trigger:
  branches:
    include:
    - qemu
  tags:
    include:
    - v*
pr:
- master
variables:
  AZURE: 'true'
  PYTHON_VERSION: 3.9
  CONDA_ENV: test-env
jobs:
###########################################
- job: QEMU
###########################################
  variables:
    COMPILER: gcc
    DEBIAN_FRONTEND: 'noninteractive'
    OS_NAME: 'linux'
    SETUP_CONDA: 'true'
  pool:
    vmImage: 'ubuntu-20.04'
  strategy:
    matrix:
      regular:
        TASK: regular
        PYTHON_VERSION: 3.6
  steps:
  - script: |
      echo "##vso[task.setvariable variable=BUILD_DIRECTORY]$BUILD_SOURCESDIRECTORY"
      echo "##vso[task.setvariable variable=LGB_VER]$(head -n 1 VERSION.txt)"
      CONDA=$HOME/miniconda
      echo "##vso[task.setvariable variable=CONDA]$CONDA"
      echo "##vso[task.prependpath]$CONDA/bin"
    displayName: 'Set variables'
  # https://github.com/microsoft/azure-pipelines-agent/issues/2043#issuecomment-687983301
  - script: |
      sudo apt-get update
      sudo apt-get install --no-install-recommends -y \
        qemu \
        qemu-user-static \
        qemu-user \
        binfmt-support
      cp /usr/bin/qemu-aarch64-static $(Build.SourcesDirectory)
    displayName: 'Install QEMU'
  - script: |
      docker run --rm --privileged multiarch/qemu-user-static:register --reset --credential yes
      ls /proc/sys/fs/binfmt_misc/
    displayName: Configure binfmt_misc
  - script: |
      docker run \
        -v "$(Build.SourcesDirectory)":"/LightGBM" \
        --rm \
        "quay.io/pypa/manylinux2014_aarch64" \
        bash \
        echo "Hello from ARM container!"
    displayName: Run docker build
